# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Journay
tagline:          'A Jekyll theme'
description:      'Welcome. Made by <a href="https://zhuanlan.zhihu.com" target="_blank">@Zacks</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
