# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Journay
tagline:          'A Jekyll theme'
description:      'Welcome to Zacks's blog. Made by <a href="https://www.zhihu.com/people/zhao-yuan-xiao-9/activities" target="_blank">@Zacks</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
